package Frames;

import Usuario.ListaUsuario;
import Usuario.Usuario;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo
 */
public class Ingresoocreacion extends javax.swing.JFrame {

   
    public Ingresoocreacion() {
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        initComponents();
        this.setLocationRelativeTo(this);
        jComboTipo.addItem("Administrador");
        jComboTipo.addItem("Usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextnomUser = new javax.swing.JTextField();
        jButtonCrear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SignOut_icon-icons.com_74704.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));
        getContentPane().add(jTextPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 220, 20));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOMBRE DE USUARIO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTRASEÑA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 107, -1));

        jTextnomUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnomUserActionPerformed(evt);
            }
        });
        getContentPane().add(jTextnomUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 220, -1));

        jButtonCrear.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/30.png"))); // NOI18N
        jButtonCrear.setText("  CREAR CUENTA");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 180, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TIPO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 107, -1));

        getContentPane().add(jComboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 183, 228, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/A.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextnomUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnomUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnomUserActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        String usuario = jTextnomUser.getText();
        String contraseña = jTextPass.getText();
        String tipo = jComboTipo.getSelectedItem().toString();
        Usuario us = new Usuario();
        if (jTextnomUser.getText().length() != 0  && jTextPass.getText().length()!= 0){
            if (Usuario.usuarioNuevo(usuario) == -1) {
            us.setUser(usuario);
            us.setPass(contraseña);
            us.setTipo(tipo);
            ListaUsuario.agregar(us);
            JOptionPane.showMessageDialog(this,"El usuario se ha registrado satisfactoriamente");
             Login abrir = new Login();
             abrir.setVisible(true);
             this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this,"Este usuario ya se encuntre registrado");
        }
        }else{
            JOptionPane.showMessageDialog(this, "Se encuentran campos Vacios");
        }
        jTextnomUser.setText("");
        jTextPass.setText("");
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JComboBox<String> jComboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jTextPass;
    private javax.swing.JTextField jTextnomUser;
    // End of variables declaration//GEN-END:variables
}
